
Encoding ---> conversion of words to vectors or numericals [ it depends on frequency of the words]
              BOW , TF-IDF , OHE , N-grams , some custom techniques
			  
Embedding ----> word into vectors [  it depends on frequency of the neural network architecture ]
                word2vec introduced by google and it is used by using neuralnetwork by default it is consists of vector size of 384
				
New technique -- > Transformers based models (sentence embedding)
                   Bert , Gemini , Elmo , open ai , MPT
				   
				   
Note : Difference between encoding and embedding are both are try to convert words into vectors or numericals but embedding is based on neuralnetwork architecture

### Embedding : [  it depends on frequency of the neural network architecture ]


1) Word2vec :  it is of 2 types CBOW and SKIPGRAM

Google word2vec : It was developed by the google and it is based on the neural network architecture and it contains 300 dimensions of word (ie : it contains 300 vectors for each word)

Based on the research if we have small data we can use "CBOW" and for large dataset we use "SKIPGRAM"

Improvement in word2vec : Increase window size 
                          Increase dimension of vector
						  Increase the training dataset
						  
2) Skipgram : 

3) Avgword2vec : it is used for sentences
                 Average word2vec take average of all the words of the vectors  in the sentences and that value taken into consideration .


Note : Sentence Embedding :
---------------------------
 We can do sentence embedding means convert into vectors by 3 ways
 
 1) sentence transformer
 
 2) langchain hugging face models
 
 3) Transformer based [Bert based]
 
 We can also decode the vectors ie: convert vectors into original form (sentences) .




Common types of encoding:
--------------------------

Encoding Type	                    Description	                                                        Example
One-Hot Encoding	                Each word or category becomes a binary vector.	                    "cat" → [0, 1, 0]
Label Encoding	                    Assigns an integer to each word/category.	                        "cat" → 1
Ordinal Encoding	                Like label encoding, but assumes some order between categories.	    "low" → 0, "high" → 2
Frequency Encoding	                Encodes based on frequency of the word/category in the data.	    "the" → 5000



Common types of Embedding:
--------------------------

Word2vec 

1) Word2vec :  it is of 2 types CBOW and SKIPGRAM

In [2]:
!pip install gensim

   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.0 MB ? eta -:--:--
    --------------------------------------- 0.5/24.0 MB 453.5 kB/s eta 0:00:52
   - -------------------------------------- 0.8/24.0 MB 589.1 kB/s eta 0:00:40
   - -------------------------------------- 1.0/24.0 MB 709.1 kB/s eta 0:00:33
   -- ------------------------------------- 1.3/24.0 MB 799.2 kB/s eta 0:00:29
   -- ------------------------------------- 1.6/24.0 MB 883.2 kB/s eta 0:00:26
   --- ------------------------------------ 1.8/24.0 MB 923.6 kB/s eta 0:00:25
   --- -----------------------------

  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [3]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

In [4]:
model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [5]:
model["satya"]

array([ 0.12597656, -0.015625  ,  0.22949219,  0.13964844,  0.05053711,
        0.14550781,  0.27929688, -0.00130463, -0.13183594,  0.12353516,
       -0.10644531, -0.07275391, -0.22167969,  0.34375   , -0.19140625,
        0.21875   ,  0.11181641, -0.0168457 , -0.04418945, -0.03979492,
       -0.06591797, -0.17089844,  0.10205078,  0.0145874 , -0.14355469,
       -0.05102539, -0.0234375 ,  0.00616455,  0.12988281, -0.16113281,
       -0.05810547, -0.140625  , -0.08837891,  0.07714844, -0.09863281,
       -0.05200195, -0.0189209 , -0.0625    ,  0.19824219, -0.05395508,
        0.02172852, -0.06079102,  0.06640625,  0.05273438, -0.08642578,
       -0.11865234, -0.22363281, -0.05493164, -0.07421875, -0.03979492,
       -0.04736328,  0.21679688, -0.02526855,  0.05395508,  0.08886719,
        0.11816406, -0.14257812, -0.31640625,  0.08251953, -0.16992188,
        0.15527344,  0.15234375,  0.17480469, -0.04785156,  0.06054688,
       -0.08544922,  0.03540039,  0.04272461,  0.14941406,  0.00

In [6]:
len(model["satya"])

300

In [7]:
model["men"]

array([-4.78515625e-02,  1.66992188e-01,  7.81250000e-02,  2.10571289e-03,
        2.25585938e-01, -2.25585938e-01, -2.09960938e-01, -3.73535156e-02,
       -1.85546875e-02,  1.94335938e-01, -3.00292969e-02, -1.77734375e-01,
        5.20019531e-02,  1.33789062e-01, -1.13769531e-01,  1.10351562e-01,
       -3.27148438e-02,  2.89916992e-03,  9.88769531e-03,  9.27734375e-02,
       -2.19726562e-01, -2.47802734e-02, -8.59375000e-02, -2.67578125e-01,
       -2.51464844e-02, -2.55859375e-01, -1.61132812e-01,  2.53906250e-01,
        5.24902344e-02, -1.00097656e-02,  1.82617188e-01,  7.61718750e-02,
       -1.60980225e-03, -3.10058594e-02, -3.32031250e-02,  1.81640625e-01,
       -3.88183594e-02, -1.83593750e-01, -8.64257812e-02,  2.20703125e-01,
       -7.11059570e-03,  8.60595703e-03,  1.73828125e-01, -9.27734375e-02,
        1.25000000e-01, -1.28906250e-01, -4.85839844e-02, -1.21093750e-01,
        8.00781250e-02,  1.05957031e-01,  1.42578125e-01,  6.78710938e-02,
        6.29882812e-02, -

In [8]:
len(model["men"])

300

In [9]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [10]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [11]:
model.most_similar("satya")

[('atma', 0.7216063141822815),
 ('smriti', 0.6725621819496155),
 ('dharam', 0.6696865558624268),
 ('Shri_Rama', 0.6682771444320679),
 ('kriya', 0.6587613224983215),
 ('mukti', 0.6582211852073669),
 ('Adhyatma', 0.6546815633773804),
 ('Gurbaani', 0.6518490314483643),
 ('Bhagwad_Geeta', 0.6501480340957642),
 ('ka_hai', 0.6466910243034363)]

In [12]:
model.similarity('man','woman')

0.76640123

In [13]:
model.similarity('man','python')

0.2097966

In [14]:
model.similarity('man','java')

0.019312028

In [15]:
model.similarity('sunny','Sunny')

0.43010473

In [16]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [17]:
vec=model['king'] - model['man'] + model['woman']

In [18]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [28]:
import nltk
from gensim.models import Word2Vec
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize

# Download required resources
nltk.download('punkt')
nltk.download('stopwords')

# Sample text data (replace this with your own text corpus)
text = "Vikram went to war. Vikram is a brave warrior. War changes everything."

# Sentence tokenization
sentences = sent_tokenize(text)

# Word tokenization and stopword removal
stop_words = set(stopwords.words('english'))
tokenized_sentences = []

for sentence in sentences:
    words = word_tokenize(sentence.lower())
    filtered_words = [word for word in words if word.isalpha() and word not in stop_words]
    tokenized_sentences.append(filtered_words)

# Train Word2Vec model
model = Word2Vec(sentences=tokenized_sentences, vector_size=100, window=5, min_count=1, workers=4)

# Words in vocabulary (note: `wv.vocab` is deprecated)
words = list(model.wv.index_to_key)
print("Vocabulary:", words)

# Find vector of a word
if 'war' in model.wv:
    vector = model.wv['war']
    print("\nVector for 'war':", vector)

# Find most similar words
if 'vikram' in model.wv:
    similar = model.wv.most_similar('vikram')
    print("\nWords most similar to 'vikram':")
    for word, score in similar:
        print(f"{word}: {score:.4f}")
else:
    print("\nWord 'vikram' not found in vocabulary.")


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chand\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chand\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Vocabulary: ['war', 'vikram', 'everything', 'changes', 'warrior', 'brave', 'went']

Vector for 'war': [-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-0

Custom Word2vec model : 
--------------------------

custom_model = gensim.models.word2vec( window =10,min_count=5,vector_size=150)

here min_count represents if the word appear minimum 5 times then only consider that word otherwise reject the word .

vector_size represents hiddenlayer vector size

window represent choose a word [Target word]  so that the 10 words before and after are surrounded  by the selected  target word .

CBOW : [ Continous Bag of Words]
-----

Predict the target word from  words

Uses multiple context words to predict one target word

Out of vocabulary issue we will face it will generate output for vocabulary words only for example the words which are not in vocab we pass that will not process 
and give output as outofvocabulary

example :
----------

"The cat sat on the mat"

CBOW Example:

Context words: ["The", "sat"]
Target word: "cat"

In [29]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
sentences= [
    "The cat sat on the mat.",
    "The dog sat on the log.",
    "The cat chased the mouse.",
    "The dog barked at the cat."
]
# Tokenize sentences
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

cbow_model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=2, min_count=1, sg=0)


## sg=0 → CBOW model (default) if sg=1 (skipgram)
## window=2 → Context window size
## vector_size=50 → Embedding size
 
## window represent choose a word [Target word]  so that the 2 words before and after are surrounded  by the selected  target word .
 
print(cbow_model.wv["cat"])  # Get vector representation of "cat"
 
print(cbow_model.wv.most_similar("cat"))

[ 1.56314243e-02 -1.90182701e-02 -4.10412991e-04  6.93756482e-03
 -1.87642663e-03  1.67613048e-02  1.80220641e-02  1.30723128e-02
 -1.42552785e-03  1.54204927e-02 -1.70695987e-02  6.41235569e-03
 -9.27880500e-03 -1.01791862e-02  7.17839133e-03  1.07407840e-02
  1.55402496e-02 -1.15301441e-02  1.48653621e-02  1.32519286e-02
 -7.42009981e-03 -1.74906123e-02  1.08772125e-02  1.30185885e-02
 -1.57406169e-03 -1.34187993e-02 -1.41712418e-02 -4.99332137e-03
  1.02863368e-02 -7.33136712e-03 -1.87386647e-02  7.65149994e-03
  9.76975355e-03 -1.28588863e-02  2.41649779e-03 -4.14937036e-03
  5.24397619e-05 -1.97659265e-02  5.38434321e-03 -9.49859712e-03
  2.17847456e-03 -3.15548526e-03  4.39163670e-03 -1.57633983e-02
 -5.43250563e-03  5.32657886e-03  1.06937252e-02 -4.78297239e-03
 -1.90195609e-02  9.01283231e-03]
[('mat', 0.19009442627429962), ('at', 0.0448918454349041), ('barked', -0.010132141411304474), ('.', -0.014458801597356796), ('chased', -0.02322026900947094), ('sat', -0.04404716566205025

 Skip-gram :
 ----------
 
 Predict context words from a target word
 
 Uses one target word to predict multiple context words
 
 Out of vocabulary issue we will face it will generate output for vocabulary words only for example the words which are not in vocab we pass that will not process 
 and give output as outofvocabulary
 
 

example :
----------

"The cat sat on the mat" 
 
 
 
 Skip-gram Example:
 -------------------

Target word: "cat"
Context words: ["The", "sat"]

In [31]:

# Tokenize sentences
tokenized_sentences = [word_tokenize(sentence) for sentence in sentences]

cbow_model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=2, min_count=1, sg=1)

cbow_model.save("cbow.model")
cbow_model = Word2Vec.load("cbow.model")    


 ##sg=0 → CBOW model (default) if sg=1 (skipgram)
 ##window=2 → Context window size
 ##vector_size=50 → Embedding size
 
 
##window represent choose a word [Target word]  so that the 2 words before and after are surrounded  by the selected  target word .


##Averageword2vec :
##Averageword2vec is a simple and effective method for generating word embeddings.
##It works by taking the average of the word vectors for all the words in a sentence or document.

##Averageword2vec works on taking average of the vector values

### Sentence embedding

1. setence transformer
2. langchain hugging
3. transformer

In [32]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

In [34]:
!pip install sentence-transformers
from sentence_transformers import SentenceTransformer

   ---------------------------------------- 0.0/10.4 MB ? eta -:--:--
   --- ------------------------------------ 0.8/10.4 MB 3.7 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/10.4 MB 3.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/10.4 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/10.4 MB 3.8 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/10.4 MB 3.8 MB/s eta 0:00:02
   ------------------- -------------------- 5.0/10.4 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 5.8/10.4 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 6.6/10.4 MB 3.8 MB/s eta 0:00:01
   ---------------------------- ----------- 7.3/10.4 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 8.1/10.4 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.9/10.4 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 9.7/10.4 MB 3.8 MB/s eta 0:00:01
   ---

c:\Users\chand\anaconda3\envs\env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [35]:
model = SentenceTransformer('all-mpnet-base-v2')

c:\Users\chand\anaconda3\envs\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\chand\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back t

In [36]:
sentences[0]

'I ate dinner.'

In [37]:
model.encode(sentences[0])

array([-1.58597678e-02,  4.59826551e-02, -1.46349585e-02, -4.85908687e-02,
       -3.60319996e-03,  3.17664109e-02, -3.27771641e-02,  2.11895313e-02,
        1.07366042e-02,  2.50182096e-02,  1.58237889e-02,  1.24069359e-02,
        1.62089840e-02, -1.30434325e-02,  4.58446629e-02,  4.40269858e-02,
        4.57802415e-02, -4.32259543e-03,  1.87806357e-02,  5.22195548e-03,
       -1.86415315e-02, -7.11804302e-03,  3.01359687e-02,  1.70695819e-02,
       -1.53764402e-02,  3.34172398e-02, -6.55884482e-03,  1.58591792e-02,
        1.37038892e-02, -2.02767160e-02,  3.26631889e-02,  5.48361661e-03,
       -3.53351422e-02, -1.06665209e-01,  1.85711565e-06,  3.66638750e-02,
       -1.71336550e-02,  3.34468447e-02, -6.43022060e-02,  6.90796226e-02,
        2.50845030e-02,  2.89430898e-02, -8.98415409e-03, -1.84546430e-02,
        2.81152073e-02, -2.34797206e-02,  1.21612307e-02,  6.25151247e-02,
       -8.58704001e-02, -1.84621708e-03,  7.95865990e-03, -8.42522830e-02,
       -2.26104409e-02,  

In [38]:
model.encode(sentences[0]).shape

(768,)

In [39]:
!pip install langchain
!pip install langchain-community

In [40]:
from langchain.embeddings import HuggingFaceEmbeddings

In [41]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [42]:


from langchain_community.embeddings import HuggingFaceEmbeddings

# Model name and configuration
embedding_model_name = "sentence-transformers/all-MiniLM-L6-v2"
model_kwargs = {"device": "cpu"}  # or "cuda" if you have a GPU

# Initialize the embedding model
embeddings = HuggingFaceEmbeddings(
    model_name=embedding_model_name,
    model_kwargs=model_kwargs
)

# Embed a single query
query_embedding = embeddings.embed_query("I love programming in Python")
print("Query embedding shape:", len(query_embedding))

# Embed a list of documents
docs = [
    "I love programming in Python",
    "Python is a great language for data science"
]
doc_embeddings = embeddings.embed_documents(docs)
print("Number of document embeddings:", len(doc_embeddings))
print("Each embedding vector length:", len(doc_embeddings[0]))


c:\Users\chand\anaconda3\envs\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\chand\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to

Query embedding shape: 384
Number of document embeddings: 2
Each embedding vector length: 384


In [43]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [44]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [45]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

c:\Users\chand\anaconda3\envs\env\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\chand\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [46]:
model=BertModel.from_pretrained("bert-base-uncased")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


In [47]:
text="follow krish and sunny savitha for genai learning"

In [48]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [49]:
input_ids=encoding["input_ids"]

In [50]:
attention_mask=encoding["attention_mask"]

In [51]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [52]:
word_embeddings

tensor([[[-0.2734, -0.1671,  0.1827,  ..., -0.1776,  0.1434,  0.2853],
         [ 0.9149, -0.0324,  0.2213,  ...,  0.2632,  0.5265,  0.0233],
         [ 0.5619, -1.2690,  0.0807,  ..., -0.9424,  0.0024, -1.2081],
         ...,
         [-0.1183, -0.4699, -0.2115,  ..., -0.4210, -0.2176, -0.3333],
         [-0.5571, -0.7545, -0.2103,  ...,  0.7741,  0.5251, -0.4931],
         [ 0.8210,  0.0588, -0.0103,  ...,  0.1527, -0.5460, -0.2349]]])

In [53]:
word_embeddings.shape

torch.Size([1, 14, 768])

In [54]:
input_ids[0]

tensor([  101,  3582, 19031,  2232,  1998, 11559,  7842,  5737,  8322,  2005,
         8991,  4886,  4083,   102])

In [55]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [56]:
decode

'follow krish and sunny savitha for genai learning'