In [1]:
print("ok")

ok



Encoding ---> conversion of words to vectors or numericals [ it depends on frequency of the words]
              BOW , TF-IDF , OHE , N-grams , some custom techniques
			  
Embedding ----> word into vectors [  it depends on frequency of the neural network architecture ]
                word2vec introduced by google and it is used by using neuralnetwork by default it is consists of vector size of 384
				
New technique -- > Transformers based models (sentence embedding)
                   Bert , Gemini , Elmo , open ai , MPT
				   
				   
Note : Difference between encoding and embedding are both are try to convert words into vectors or numericals but embedding is based on neuralnetwork architecture


Encoding:
--------

Encoding is the process of converting data from one format to another. 
It often transforms categorical or textual data into numerical format to be used in machine learning models.


Types of Encoding:
-----------------

Label Encoding:
---------------

Converts each unique category to an integer.


Red → 0, Blue → 1, Green → 2


Usage: Ordinal data (like size: Small, Medium, Large).



One-Hot Encoding:
---------------

Creates a binary column for each category.


Red → [1,0,0], Blue → [0,1,0], Green → [0,0,1]


Usage: Categorical data without inherent order.



Binary Encoding:
----------------

Converts categories to binary numbers.


Category A → 001, B → 010, C → 011

Usage: High-cardinality categorical variables.



Ordinal Encoding:
----------------

Encodes categories with a meaningful order.


Low → 1, Medium → 2, High → 3

Usage: When the order of categories matters.



Frequency Encoding:
------------------

Encodes categories based on their frequency in the dataset.


Red (10 times) → 0.1, Blue (20 times) → 0.2

Usage: When the frequency of occurrence is important.



Target Encoding:
---------------

Encodes categories based on the mean of the target variable.


Category A → 0.3 (mean of target for category A)

Usage: Handling categorical variables with respect to the target.




#### Encoding : [ it depends on frequency of the words]

In [6]:
pip install scikit-learn


   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.1 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.8/11.1 MB 4.0 MB/s eta 0:00:03
   --------- ------------------------------ 2.6/11.1 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.4/11.1 MB 3.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/11.1 MB 3.9 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.1 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.1 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 3.9 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/11.1 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.1 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 9.7/11.1 MB 3.9 MB/s eta 0:00:01
   ---

In [7]:

from sklearn.preprocessing import LabelEncoder

labels = ['apple', 'banana', 'cherry']
encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(labels)

print("Encoded Labels:", encoded_labels)
print("Inverse Transform:", encoder.inverse_transform([0, 1, 2]))

Encoded Labels: [0 1 2]
Inverse Transform: ['apple' 'banana' 'cherry']


In [8]:
import pandas as pd

In [9]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [10]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
BOW=CountVectorizer()

In [13]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [14]:
document_matrix=BOW.fit_transform(data["text"])

In [15]:
document_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

### Alphabatical sequence

In [16]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [17]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]])

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

comment, cricket, give, people, watch

D2-> cricket watch cricket

0, 2, 0, 0, 1


In [18]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

In [19]:
document_matrix[2].toarray()

array([[1, 0, 1, 1, 0]])

In [20]:
document_matrix[3].toarray()

array([[1, 1, 1, 0, 0]])

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
bigram=CountVectorizer(ngram_range=(2,2))

In [23]:
bigramvocab=bigram.fit_transform(data["text"])

In [24]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [25]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [26]:
trigram=CountVectorizer(ngram_range=(3,3))

In [27]:
trigramvocab=trigram.fit_transform(data["text"])

In [28]:
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [29]:
mix=CountVectorizer(ngram_range=(1,3))

In [30]:
mix_vocab=mix.fit_transform(data["text"])

In [31]:
mix.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

In [35]:
sentences=["people watch cricket","cricket watch cricket","people give comment","cricket give comment"]

In [36]:
from nltk.tokenize import word_tokenize
from nltk.util import ngrams

In [45]:

# sentences is already tokenized, so no need to tokenize again
print(sentences)

[['people', 'watch', 'cricket'], ['cricket', 'watch', 'cricket'], ['people', 'give', 'comment'], ['cricket', 'give', 'comment']]


In [46]:
from sklearn.feature_extraction.text import CountVectorizer
bigram=CountVectorizer(ngram_range=(2,2))
trigram=CountVectorizer(ngram_range=(3,3))
mix=CountVectorizer(ngram_range=(1,3))
bigramvocab=bigram.fit_transform(data["text"])
data["text"]

import nltk

from nltk.util import bigrams,trigrams,ngrams

bigrams = list(nltk.bigrams(sentence))

trigrams = list(nltk.trigrams(sentence))

nrams = list(nltk.ngrams(sentence,4))

In [47]:
print(sentences)
print(bigrams)  
print(trigrams)
print(nrams)

[['people', 'watch', 'cricket'], ['cricket', 'watch', 'cricket'], ['people', 'give', 'comment'], ['cricket', 'give', 'comment']]
[('people watch cricket', 'cricket watch cricket'), ('cricket watch cricket', 'people give comment'), ('people give comment', 'cricket give comment')]
[('people watch cricket', 'cricket watch cricket', 'people give comment'), ('cricket watch cricket', 'people give comment', 'cricket give comment')]
[('people watch cricket', 'cricket watch cricket', 'people give comment', 'cricket give comment')]


In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf=TfidfVectorizer()

In [50]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [51]:
import numpy as np

In [52]:
np.log(4/3)

np.float64(0.28768207245178085)

In [53]:
(1/3)*np.log(4/3)

np.float64(0.09589402415059362)

In [54]:
feature_names = tfidf.get_feature_names_out()

print("Feature Names:", feature_names)


Feature Names: ['comment' 'cricket' 'give' 'people' 'watch']


In [55]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])

In [56]:
np.log10(4/3)*(1/3)


np.float64(0.041646245536099975)